package Hibernate;
// Generated 2023-06-28 22:27:58 by Hibernate Tools 4.3.1



/**
 * Wcy20kc1s0Wiszniewski generated by hbm2java
 */
public class Wcy20kc1s0Wiszniewski  implements java.io.Serializable {


     private int id;
     private String autor;
     private String hash;

    public Wcy20kc1s0Wiszniewski() {
    }

    public Wcy20kc1s0Wiszniewski(int id, String autor, String hash) {
       this.id = id;
       this.autor = autor;
       this.hash = hash;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getAutor() {
        return this.autor;
    }
    
    public void setAutor(String autor) {
        this.autor = autor;
    }
    public String getHash() {
        return this.hash;
    }
    
    public void setHash(String hash) {
        this.hash = hash;
    }




}


